### ISSUE TITLE
Issue with V-73509

### ISSUE THREAD

**Issue by burnsjared0415** [mitre/microsoft-windows-server-2016-stig-baseline#28]
Issues is that the registry for windows and inspec registry_key don't align on slashes, need to update the code to have:
variables to be added for gsub to work
keyvalue_netlogon = '\\\\*\\NETLOGON'
 keyvalue_sysvol = '\\\\*\\SYSVOL'

in both describe statements
 it { should have_property keyvalue_sysvol.gsub('\\', '\\\\\\\\') }
      its (keyvalue_sysvol.gsub('\\', '\\\\\\\\')) { should cmp 'RequireMutualAuthentication=1, RequireIntegrity=1'}

**Comment by karikarshivani** [comment]
From my tests, it looks like the existing code is correct. I did clean it up a little, and here are the results for both approaches (2019 and 2016):

[DC_V-73509_2019_Pass.json.txt](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/files/6993704/DC_V-73509_2019_Pass.json.txt)
[DC_V-73509_Pass.json.txt](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/files/6993705/DC_V-73509_Pass.json.txt)

![Screen Shot 2021-08-16 at 11 54 24 AM](https://user-images.githubusercontent.com/11844975/129592631-5d9afcf7-782f-47b7-8498-2758803128d0.png)

@burnsjared0415 please let me know if this looks good to you.

**Comment by karikarshivani** [comment]
**Update:** Both the previous and the new approaches worked when the control was executed from a Windows runner.

![Screen Shot 2021-08-23 at 2 25 43 PM](https://user-images.githubusercontent.com/11844975/130497806-9f014b8c-a688-4190-9c3b-239a2b3be4ea.png)

Since the new approach worked from both the runners, [a new issue](https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/issues/31) for Windows 2019 has been created to use the new approach.
